import { PropsWithChildren } from "react";
import SidebarLayout from "~/layouts/SidebarLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: PropsWithChildren) {
  return <SidebarLayout>{children}</SidebarLayout>;
}
