interface Asset {
  _symbol: string;
  precision: number;
  collateralQ: string;
  utilization: string;
  borrowApy: string;
  supplyApy: string;
}

export const assets: Record<string, Asset> = {
  "1": {
    _symbol: "USDT",
    precision: 6,
    collateralQ: "60%",
    utilization: "80%",
    borrowApy: "4.5%",
    supplyApy: "2%",
  },
  "2": {
    _symbol: "WBTC",
    precision: 6,
    collateralQ: "40%",
    utilization: "70%",
    borrowApy: "3.5%",
    supplyApy: "2.5%",
  },
  "3": {
    _symbol: "WETH",
    precision: 6,
    collateralQ: "42%",
    utilization: "73%",
    borrowApy: "3.1%",
    supplyApy: "3.7%",
  },
  "4": {
    _symbol: "BNB",
    precision: 6,
    collateralQ: "55%",
    utilization: "78%",
    borrowApy: "4.2%",
    supplyApy: "1.8%",
  },
  "5": {
    _symbol: "XRP",
    precision: 6,
    collateralQ: "38%",
    utilization: "65%",
    borrowApy: "3.8%",
    supplyApy: "2.2%",
  },
  "6": {
    _symbol: "BUSD",
    precision: 6,
    collateralQ: "62%",
    utilization: "82%",
    borrowApy: "4.7%",
    supplyApy: "1.9%",
  },
  "7": {
    _symbol: "ADA",
    precision: 6,
    collateralQ: "45%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.7%",
  },
  "8": {
    _symbol: "SOL",
    precision: 6,
    collateralQ: "50%",
    utilization: "75%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "9": {
    _symbol: "DOGE",
    precision: 6,
    collateralQ: "35%",
    utilization: "60%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "10": {
    _symbol: "MATIC",
    precision: 6,
    collateralQ: "48%",
    utilization: "74%",
    borrowApy: "4.0%",
    supplyApy: "2.9%",
  },
  "11": {
    _symbol: "DOT",
    precision: 6,
    collateralQ: "52%",
    utilization: "77%",
    borrowApy: "4.3%",
    supplyApy: "2.0%",
  },
  "12": {
    _symbol: "DAI",
    precision: 6,
    collateralQ: "65%",
    utilization: "85%",
    borrowApy: "4.8%",
    supplyApy: "1.7%",
  },
  "13": {
    _symbol: "SHIB",
    precision: 6,
    collateralQ: "30%",
    utilization: "55%",
    borrowApy: "3.4%",
    supplyApy: "2.6%",
  },
  "14": {
    _symbol: "TRX",
    precision: 6,
    collateralQ: "41%",
    utilization: "68%",
    borrowApy: "3.7%",
    supplyApy: "2.3%",
  },
  "15": {
    _symbol: "AVAX",
    precision: 6,
    collateralQ: "47%",
    utilization: "73%",
    borrowApy: "3.9%",
    supplyApy: "2.8%",
  },
  "16": {
    _symbol: "LTC",
    precision: 6,
    collateralQ: "58%",
    utilization: "80%",
    borrowApy: "4.4%",
    supplyApy: "1.9%",
  },
  "17": {
    _symbol: "UNI",
    precision: 6,
    collateralQ: "43%",
    utilization: "70%",
    borrowApy: "3.8%",
    supplyApy: "2.5%",
  },
  "18": {
    _symbol: "LINK",
    precision: 6,
    collateralQ: "51%",
    utilization: "76%",
    borrowApy: "4.2%",
    supplyApy: "2.1%",
  },
  "19": {
    _symbol: "ATOM",
    precision: 6,
    collateralQ: "49%",
    utilization: "75%",
    borrowApy: "4.0%",
    supplyApy: "2.9%",
  },
  "20": {
    _symbol: "ETC",
    precision: 6,
    collateralQ: "37%",
    utilization: "63%",
    borrowApy: "3.5%",
    supplyApy: "2.4%",
  },
  "21": {
    _symbol: "XLM",
    precision: 6,
    collateralQ: "40%",
    utilization: "67%",
    borrowApy: "3.7%",
    supplyApy: "2.2%",
  },
  "22": {
    _symbol: "NEAR",
    precision: 6,
    collateralQ: "46%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.7%",
  },
  "23": {
    _symbol: "FIL",
    precision: 6,
    collateralQ: "53%",
    utilization: "78%",
    borrowApy: "4.3%",
    supplyApy: "2.0%",
  },
  "24": {
    _symbol: "VET",
    precision: 6,
    collateralQ: "39%",
    utilization: "66%",
    borrowApy: "3.6%",
    supplyApy: "2.3%",
  },
  "25": {
    _symbol: "ALGO",
    precision: 6,
    collateralQ: "44%",
    utilization: "71%",
    borrowApy: "3.8%",
    supplyApy: "2.6%",
  },
  "26": {
    _symbol: "HBAR",
    precision: 6,
    collateralQ: "50%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "27": {
    _symbol: "ICP",
    precision: 6,
    collateralQ: "36%",
    utilization: "62%",
    borrowApy: "3.5%",
    supplyApy: "2.5%",
  },
  "28": {
    _symbol: "MANA",
    precision: 6,
    collateralQ: "42%",
    utilization: "69%",
    borrowApy: "3.7%",
    supplyApy: "2.4%",
  },
  "29": {
    _symbol: "SAND",
    precision: 6,
    collateralQ: "48%",
    utilization: "74%",
    borrowApy: "4.0%",
    supplyApy: "2.8%",
  },
  "30": {
    _symbol: "AXS",
    precision: 6,
    collateralQ: "54%",
    utilization: "79%",
    borrowApy: "4.4%",
    supplyApy: "1.9%",
  },
  "31": {
    _symbol: "THETA",
    precision: 6,
    collateralQ: "38%",
    utilization: "65%",
    borrowApy: "3.6%",
    supplyApy: "2.3%",
  },
  "32": {
    _symbol: "XTZ",
    precision: 6,
    collateralQ: "45%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.6%",
  },
  "33": {
    _symbol: "EGLD",
    precision: 6,
    collateralQ: "51%",
    utilization: "77%",
    borrowApy: "4.2%",
    supplyApy: "2.0%",
  },
  "34": {
    _symbol: "FLOW",
    precision: 6,
    collateralQ: "40%",
    utilization: "67%",
    borrowApy: "3.7%",
    supplyApy: "2.2%",
  },
  "35": {
    _symbol: "AAVE",
    precision: 6,
    collateralQ: "47%",
    utilization: "73%",
    borrowApy: "4.0%",
    supplyApy: "2.7%",
  },
  "36": {
    _symbol: "EOS",
    precision: 6,
    collateralQ: "53%",
    utilization: "78%",
    borrowApy: "4.3%",
    supplyApy: "1.9%",
  },
  "37": {
    _symbol: "XMR",
    precision: 6,
    collateralQ: "39%",
    utilization: "66%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "38": {
    _symbol: "GRT",
    precision: 6,
    collateralQ: "46%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "39": {
    _symbol: "LRC",
    precision: 6,
    collateralQ: "50%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "40": {
    _symbol: "CRV",
    precision: 6,
    collateralQ: "37%",
    utilization: "63%",
    borrowApy: "3.5%",
    supplyApy: "2.3%",
  },
  "41": {
    _symbol: "BCH",
    precision: 6,
    collateralQ: "43%",
    utilization: "70%",
    borrowApy: "3.8%",
    supplyApy: "2.6%",
  },
  "42": {
    _symbol: "ENJ",
    precision: 6,
    collateralQ: "49%",
    utilization: "75%",
    borrowApy: "4.0%",
    supplyApy: "2.8%",
  },
  "43": {
    _symbol: "DASH",
    precision: 6,
    collateralQ: "55%",
    utilization: "80%",
    borrowApy: "4.4%",
    supplyApy: "1.9%",
  },
  "44": {
    _symbol: "ZEC",
    precision: 6,
    collateralQ: "41%",
    utilization: "68%",
    borrowApy: "3.7%",
    supplyApy: "2.2%",
  },
  "45": {
    _symbol: "KSM",
    precision: 6,
    collateralQ: "48%",
    utilization: "74%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "46": {
    _symbol: "CHZ",
    precision: 6,
    collateralQ: "52%",
    utilization: "77%",
    borrowApy: "4.2%",
    supplyApy: "2.0%",
  },
  "47": {
    _symbol: "COMP",
    precision: 6,
    collateralQ: "38%",
    utilization: "65%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "48": {
    _symbol: "SNX",
    precision: 6,
    collateralQ: "45%",
    utilization: "72%",
    borrowApy: "3.8%",
    supplyApy: "2.7%",
  },
  "49": {
    _symbol: "BAT",
    precision: 6,
    collateralQ: "51%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "50": {
    _symbol: "MKR",
    precision: 6,
    collateralQ: "40%",
    utilization: "67%",
    borrowApy: "3.7%",
    supplyApy: "2.3%",
  },
  "51": {
    _symbol: "NEO",
    precision: 6,
    collateralQ: "47%",
    utilization: "73%",
    borrowApy: "4.0%",
    supplyApy: "2.6%",
  },
  "52": {
    _symbol: "QTUM",
    precision: 6,
    collateralQ: "53%",
    utilization: "78%",
    borrowApy: "4.3%",
    supplyApy: "1.9%",
  },
  "53": {
    _symbol: "ZIL",
    precision: 6,
    collateralQ: "39%",
    utilization: "66%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "54": {
    _symbol: "IOST",
    precision: 6,
    collateralQ: "46%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "55": {
    _symbol: "OMG",
    precision: 6,
    collateralQ: "50%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "56": {
    _symbol: "ONT",
    precision: 6,
    collateralQ: "37%",
    utilization: "63%",
    borrowApy: "3.5%",
    supplyApy: "2.3%",
  },
  "57": {
    _symbol: "ZRX",
    precision: 6,
    collateralQ: "43%",
    utilization: "70%",
    borrowApy: "3.8%",
    supplyApy: "2.6%",
  },
  "58": {
    _symbol: "ICX",
    precision: 6,
    collateralQ: "49%",
    utilization: "75%",
    borrowApy: "4.0%",
    supplyApy: "2.8%",
  },
  "59": {
    _symbol: "SC",
    precision: 6,
    collateralQ: "55%",
    utilization: "80%",
    borrowApy: "4.4%",
    supplyApy: "1.9%",
  },
  "60": {
    _symbol: "WAVES",
    precision: 6,
    collateralQ: "41%",
    utilization: "68%",
    borrowApy: "3.7%",
    supplyApy: "2.2%",
  },
  "61": {
    _symbol: "BTG",
    precision: 6,
    collateralQ: "48%",
    utilization: "74%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "62": {
    _symbol: "DCR",
    precision: 6,
    collateralQ: "52%",
    utilization: "77",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "63": {
    _symbol: "HOT",
    precision: 6,
    collateralQ: "38%",
    utilization: "65%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "64": {
    _symbol: "LSK",
    precision: 6,
    collateralQ: "45%",
    utilization: "72%",
    borrowApy: "3.8%",
    supplyApy: "2.7%",
  },
  "65": {
    _symbol: "RVN",
    precision: 6,
    collateralQ: "51%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "66": {
    _symbol: "NANO",
    precision: 6,
    collateralQ: "40%",
    utilization: "67%",
    borrowApy: "3.7%",
    supplyApy: "2.3%",
  },
  "67": {
    _symbol: "BCD",
    precision: 6,
    collateralQ: "47%",
    utilization: "73%",
    borrowApy: "4.0%",
    supplyApy: "2.6%",
  },
  "68": {
    _symbol: "XEM",
    precision: 6,
    collateralQ: "53%",
    utilization: "78%",
    borrowApy: "4.3%",
    supplyApy: "1.9%",
  },
  "69": {
    _symbol: "AR",
    precision: 6,
    collateralQ: "39%",
    utilization: "66%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "70": {
    _symbol: "STX",
    precision: 6,
    collateralQ: "46%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "71": {
    _symbol: "KAVA",
    precision: 6,
    collateralQ: "50%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "72": {
    _symbol: "TFUEL",
    precision: 6,
    collateralQ: "37%",
    utilization: "63%",
    borrowApy: "3.5%",
    supplyApy: "2.3%",
  },
  "73": {
    _symbol: "ONE",
    precision: 6,
    collateralQ: "43%",
    utilization: "70%",
    borrowApy: "3.8%",
    supplyApy: "2.6%",
  },
  "74": {
    _symbol: "CEL",
    precision: 6,
    collateralQ: "49%",
    utilization: "75%",
    borrowApy: "4.0%",
    supplyApy: "2.8%",
  },
  "75": {
    _symbol: "ZEN",
    precision: 6,
    collateralQ: "55%",
    utilization: "80%",
    borrowApy: "4.4%",
    supplyApy: "1.9%",
  },
  "76": {
    _symbol: "CKB",
    precision: 6,
    collateralQ: "41%",
    utilization: "68%",
    borrowApy: "3.7%",
    supplyApy: "2.2%",
  },
  "77": {
    _symbol: "HNT",
    precision: 6,
    collateralQ: "48%",
    utilization: "74%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "78": {
    _symbol: "IOTX",
    precision: 6,
    collateralQ: "52%",
    utilization: "77%",
    borrowApy: "4.2%",
    supplyApy: "2.0%",
  },
  "79": {
    _symbol: "SRM",
    precision: 6,
    collateralQ: "38%",
    utilization: "65%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "80": {
    _symbol: "ANT",
    precision: 6,
    collateralQ: "45%",
    utilization: "72%",
    borrowApy: "3.8%",
    supplyApy: "2.7%",
  },
  "81": {
    _symbol: "CENNZ",
    precision: 6,
    collateralQ: "51%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "82": {
    _symbol: "BTCV",
    precision: 6,
    collateralQ: "40%",
    utilization: "67%",
    borrowApy: "3.7%",
    supplyApy: "2.3%",
  },
  "83": {
    _symbol: "XVS",
    precision: 6,
    collateralQ: "47%",
    utilization: "73%",
    borrowApy: "4.0%",
    supplyApy: "2.6%",
  },
  "84": {
    _symbol: "DGB",
    precision: 6,
    collateralQ: "53%",
    utilization: "78%",
    borrowApy: "4.3%",
    supplyApy: "1.9%",
  },
  "85": {
    _symbol: "SCRT",
    precision: 6,
    collateralQ: "39%",
    utilization: "66%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "86": {
    _symbol: "SYS",
    precision: 6,
    collateralQ: "46%",
    utilization: "72%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "87": {
    _symbol: "REN",
    precision: 6,
    collateralQ: "50%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "88": {
    _symbol: "ARK",
    precision: 6,
    collateralQ: "37%",
    utilization: "63%",
    borrowApy: "3.5%",
    supplyApy: "2.3%",
  },
  "89": {
    _symbol: "STEEM",
    precision: 6,
    collateralQ: "43%",
    utilization: "70%",
    borrowApy: "3.8%",
    supplyApy: "2.6%",
  },
  "90": {
    _symbol: "BTS",
    precision: 6,
    collateralQ: "49%",
    utilization: "75%",
    borrowApy: "4.0%",
    supplyApy: "2.8%",
  },
  "91": {
    _symbol: "XVG",
    precision: 6,
    collateralQ: "55%",
    utilization: "80%",
    borrowApy: "4.4%",
    supplyApy: "1.9%",
  },
  "92": {
    _symbol: "ICN",
    precision: 6,
    collateralQ: "41%",
    utilization: "68%",
    borrowApy: "3.7%",
    supplyApy: "2.2%",
  },
  "93": {
    _symbol: "MAID",
    precision: 6,
    collateralQ: "48%",
    utilization: "74%",
    borrowApy: "3.9%",
    supplyApy: "2.5%",
  },
  "94": {
    _symbol: "NXT",
    precision: 6,
    collateralQ: "52%",
    utilization: "77%",
    borrowApy: "4.2%",
    supplyApy: "2.0%",
  },
  "95": {
    _symbol: "RDD",
    precision: 6,
    collateralQ: "38%",
    utilization: "65%",
    borrowApy: "3.6%",
    supplyApy: "2.4%",
  },
  "96": {
    _symbol: "GAME",
    precision: 6,
    collateralQ: "45%",
    utilization: "72%",
    borrowApy: "3.8%",
    supplyApy: "2.7%",
  },
  "97": {
    _symbol: "REP",
    precision: 6,
    collateralQ: "51%",
    utilization: "76%",
    borrowApy: "4.1%",
    supplyApy: "2.1%",
  },
  "98": {
    _symbol: "GNO",
    precision: 6,
    collateralQ: "40%",
    utilization: "67%",
    borrowApy: "3.7%",
    supplyApy: "2.3%",
  },
  "99": {
    _symbol: "MLN",
    precision: 6,
    collateralQ: "47%",
    utilization: "73%",
    borrowApy: "4.0%",
    supplyApy: "2.6%",
  },
  "100": {
    _symbol: "SNT",
    precision: 6,
    collateralQ: "53%",
    utilization: "78%",
    borrowApy: "4.3%",
    supplyApy: "1.9%",
  },
};
