import { PropsWithChildren } from "react";
import { NextIntlClientProvider } from "next-intl";
import ReactQueryProvider from "~/providers/ReactQueryProvider";
import "~/sass/globals.scss";
import ThemeProvider from "~/providers/ThemeProvider";
import { fonts } from "~/assets/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fonts}>
        <ThemeProvider>
          <ReactQueryProvider>
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
