import { RootLayout } from "@repo/ui";

import { PropsWithChildren } from "react";
import { NextIntlClientProvider } from "next-intl";
import ReactQueryProvider from "~/providers/ReactQueryProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <NextIntlClientProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
