// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Dashboard": {
    "test": "Hi"
  },
  "Auth": {
    "inValidPassword": "Invalid password"
  },
  "WalletModal": {
    "title": "Connect a wallet",
    "connectButton": "Connect",
    "disconnectButton": "Disconnect"
  }
};
export default messages;