import { NextRequest, NextResponse } from "next/server";

export type Middleware = (req: NextRequest) => Promise<NextResponse | void>;
export type Locale = "en" | "se" | "ar";
export type Icon =
  | "arrow-down"
  | "arrow-left"
  | "arrow-right"
  | "arrow-right-up"
  | "arrow-up"
  | "arrow-up-down"
  | "bank"
  | "bell"
  | "book-open"
  | "check"
  | "chevron-down"
  | "chevron-right"
  | "chevron-up"
  | "close"
  | "coins"
  | "copy"
  | "discord"
  | "dots-three"
  | "duotone"
  | "file-magnifying-glass"
  | "gas-pump"
  | "gear-six"
  | "glob"
  | "home"
  | "info"
  | "list"
  | "mail"
  | "moon"
  | "plus"
  | "search"
  | "sign-out"
  | "square-half"
  | "store"
  | "sun"
  | "swap"
  | "swimming-pool"
  | "telegram"
  | "user"
  | "wallet"
  | "x";
